### PR TITLE
Updates to walk and watch to fix issues with symlinks and hidden files

### LINKED ISSUE #39: Add files prefixed with `.` to the default ignore rules

### LINKED ISSUE #40: Walk method breaks when trying to process hidden files
The `processFiles` method in the walk module chokes when passed a list of files that includes hidden files/symlinks.

```
[Error: ENOENT: no such file or directory, stat '/Users/mtalley/HubSpot/Prod/hubspot-cms-tools/tmp/timeline-test-app/node_modules/node-releases/node_modules/.bin/semver'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/Users/mtalley/HubSpot/Prod/hubspot-cms-tools/tmp/timeline-test-app/node_modules/node-releases/node_modules/.bin/semver'
} /Users/mtalley/HubSpot/Prod/hubspot-cms-tools/tmp/timeline-test-app/node_modules/node-releases/node_modules/.bin/semver
/Users/mtalley/HubSpot/Prod/hubspot-cms-tools/packages/cms-lib/lib/walk.js:18
            if (stats.isDirectory()) {
                      ^

TypeError: Cannot read property 'isDirectory' of undefined
    at /Users/mtalley/HubSpot/Prod/hubspot-cms-tools/packages/cms-lib/lib/walk.js:18:23
    at FSReqCallback.oncomplete (fs.js:158:21)
error Command failed with exit code 1.
```

Talking to @gcorne it was suggested that we ignore the hidden files/symlinks here.

### PR DESCRIPTION
**Pull request by miketalley**
Fixes #39 
Fixes #40 

### What this PR does
- Skips symlinks when running walk on a dir
- Updates watch task so it ignores hidden files/folders
- Adds tests for ignoreRules
- Adds more rules to ignoreRules based on those in junk library(https://github.com/sindresorhus/junk/blob/master/index.js#L3)

### CODE REVIEW

**Comment by gcorne** [comment]
Is there a reason we shouldn’t use `ignoreRules` so that ignoring hidden files happens everywhere?

File: packages/cms-lib/lib/walk.js [hunk 1]
```diff
@@ -7,10 +7,13 @@ function walk(dir) {
       files.map(file => {
         return new Promise((resolve, reject) => {
           const filepath = path.join(dir, file);
-          fs.stat(filepath, (error, stats) => {
+          fs.lstat(filepath, (error, stats) => {
             if (error) {
               reject(error);
             }
+            if (stats.isSymbolicLink()) {
+              resolve(filepath);
```
Comment (gcorne) [inline packages/cms-lib/lib/walk.js]: It looks like this only handles file links and will result in the linked file being uploaded. I am not sure that is what we want.

File: packages/cms-lib/ignoreRules.js [hunk 2]
```diff
@@ -3,7 +3,10 @@ const path = require('path');
 const ignore = require('ignore');
 const findup = require('findup-sync');
 
-const ignoreRules = ignore().add('node_modules');
+const hiddenFilesRegEx = /(^|\/)\.[^/.]/g;
```
Comment (gcorne) [inline packages/cms-lib/ignoreRules.js]: I am pretty sure that this could be the string '.*' but might be worth adding a test or two to confirm.

File: packages/cms-lib/lib/walk.js (hunk 1 above)
Comment (miketalley) [reply packages/cms-lib/lib/walk.js]: added code to reject symlinks and also catch and log errors during walk process -- open to ideas for improving!

File: packages/cms-lib/lib/walk.js [hunk 3]
```diff
@@ -1,22 +1,31 @@
...
+const { logger } = require('../logger');
 
 function walk(dir) {
   const processFiles = files => {
     return Promise.all(
       files.map(file => {
         return new Promise((resolve, reject) => {
           const filepath = path.join(dir, file);
-          fs.stat(filepath, (error, stats) => {
+          fs.lstat(filepath, (error, stats) => {
```
Comment (corymartin) [inline packages/cms-lib/lib/walk.js]: FYI going forward, [`fs-extra`](https://www.npmjs.com/package/fs-extra) is already a project dep.  It promisifies most functions from `fs` and adds a some convenience functions.

File: packages/cms-lib/ignoreRules.js [hunk 4]
```diff
@@ -3,7 +3,10 @@ const path = require('path');
 const ignore = require('ignore');
 const findup = require('findup-sync');
 
-const ignoreRules = ignore().add('node_modules');
+const ignoreRules = ignore().add([
+  'node_modules', // dependencies
+  '.*', // hidden files/folders
+]);
```
Comment (corymartin) [inline packages/cms-lib/ignoreRules.js]: Perhaps we should also use the [`junk`](https://www.npmjs.com/package/junk) package or something similar.
It blacklists some other things we don't care about https://github.com/sindresorhus/junk/blob/master/index.js#L3

Comment (miketalley) [reply packages/cms-lib/ignoreRules.js]: That is a useful package -- it looks like it only works with regex though. That may make it tricky to use with `ignore` because regex is not supported. :(

File: packages/cms-lib/lib/walk.js (hunk 3 above)
Comment (miketalley) [reply packages/cms-lib/lib/walk.js]: I switched over to using `fs-extra` and making everything sync, but then rolled back due to potential performance issues.

We are walking many files(potentially) and blocking the thread for each one could really slow things down. I think using `fs-extra` is a good idea going forward, but for now it's a simpler change without it.

File: packages/cms-lib/ignoreRules.js (hunk 4 above)
Comment (gcorne) [reply packages/cms-lib/ignoreRules.js]: I think we can use it as a source of inspiration and add rules to our own system.

File: packages/cms-lib/lib/walk.js [hunk 5]
```diff
@@ -1,38 +1,74 @@
...
-      })
-    );
+      } else if (stats.isFile()) {
+        resolve({
+          filepath,
+          type: STAT_TYPES.FILE,
+        });
+      }
+    });
+  }).catch(logger.error);
```
Comment (gcorne) [inline packages/cms-lib/lib/walk.js]: I think we should remove the catch and logging here.

File: packages/cms-lib/lib/walk.js [hunk 6]
```diff
@@ -1,38 +1,74 @@
...
+};
+
+const filesDataReducer = (all, fileData) => {
+  try {
```
Comment (gcorne) [inline packages/cms-lib/lib/walk.js]: What kinds of exceptions do we expect to be thrown here?

File: packages/cms-lib/lib/walk.js [hunk 7]
```diff
@@ -1,38 +1,74 @@
...
+          filepath,
+          type: STAT_TYPES.SYMBOLIC_LINK,
+        });
+      }
+      if (stats.isDirectory()) {
+        walk(filepath).then(fileContents => {
+          return resolve({
+            filepath,
+            type: STAT_TYPES.DIRECTORY,
+            fileContents,
```
Comment (gcorne) [inline packages/cms-lib/lib/walk.js]: I don't think that `fileContents` is the best name here. I think either `files` or `folderContent` is more accurate.

File: packages/cms-lib/lib/walk.js [hunk 8]
```diff
@@ -1,38 +1,74 @@
...
+        resolve({
+          filepath,
+          type: STAT_TYPES.FILE,
+        });
+      }
+    });
+  }).catch(logger.error);
+};
+
+const filesDataReducer = (all, fileData) => {
```
Comment (gcorne) [inline packages/cms-lib/lib/walk.js]: I think `all` could be clearer maybe something like `allFiles`?

File: packages/cms-lib/lib/walk.js (hunk 6 above)
Comment (miketalley) [reply packages/cms-lib/lib/walk.js]: Good point, I think perhaps I left this in from a previous iteration. Will remove.

File: packages/cms-lib/ignoreRules.js [hunk 9]
```diff
@@ -3,7 +3,29 @@ const path = require('path');
 const ignore = require('ignore');
 const findup = require('findup-sync');
 
-const ignoreRules = ignore().add('node_modules');
+// Rules used by ignore do not allow RegEx -- we are basing most of this list
+// on the Junk library, which uses RegEx https://github.com/sindresorhus/junk/blob/master/index.js#L3
+const ignoreList = [
+  '**/node_modules', // dependencies
+  '**/.*', // hidden files/folders
+  '**/npm-debug.log', // Error log for npm
```
Comment (gcorne) [inline packages/cms-lib/ignoreRules.js]: Let's change this to `**/*.log`

File: packages/cms-lib/lib/walk.js [hunk 10]
```diff
@@ -1,38 +1,68 @@
...
+
+const filesDataReducer = (allFiles, fileData) => {
+  switch (fileData.type) {
+    case STAT_TYPES.FILE:
+      return allFiles.concat(fileData.filepath);
+    case STAT_TYPES.DIRECTORY:
+      return allFiles.concat(fileData.fileContents);
+    case STAT_TYPES.SYMBOLIC_LINK:
+      // Skip symlinks
+      return allFiles;
```
Comment (corymartin) [inline packages/cms-lib/lib/walk.js]: Minor nit: this could fall-through to the default case.
