### PR TITLE
Make sure existing hubdb file is valid

### LINKED ISSUE #187: Error when fetching HubDB table to existing dir
If you try to fetch a Hubdb table into an existing directory (like `hs hubdb fetch 1739916 folder`), you get the error:
```
[ERROR] Error: EISDIR: illegal operation on a directory, open '/Users/wspiro/DESKTOP_TEMP/local-cms-dev/folder'
    at Object.openSync (fs.js:440:3)
    at Object.writeFileSync (fs.js:1265:35)
    at downloadHubDbTable (/usr/local/lib/node_modules/@hubspot/cms-cli/node_modules/@hubspot/cms-lib/hubdb.js:166:12)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Command.<anonymous> (/usr/local/lib/node_modules/@hubspot/cms-cli/commands/hubdb.js:92:9) {
  errno: -21,
  syscall: 'open',
  code: 'EISDIR',
  path: '/Users/wspiro/DESKTOP_TEMP/local-cms-dev/folder'
```

### PR DESCRIPTION
**Pull request by anthmatic**
When running `hs hubdb fetch` this validates that if `<dest>` exists, it's a valid file

image

Fixes #187

### CODE REVIEW

File: packages/cms-lib/hubdb.js [hunk 1]
```diff
@@ -141,6 +141,10 @@ function convertToJSON(table, rows) {
 }
 
 async function downloadHubDbTable(portalId, tableId, dest) {
+  if (fs.pathExistsSync(dest)) {
```
Comment (gcorne) [inline packages/cms-lib/hubdb.js:144]: How do we want to handle the situation where `dest` is not an existing file?

Comment (anthmatic) [reply packages/cms-lib/hubdb.js:144]: Currently if `dest` isn't an existing path, it will get created. Are you thinking that we should still validate that `dest` has a `.json` extension?

Comment (gcorne) [reply packages/cms-lib/hubdb.js:144]: Yeah, I think so.

File: packages/cms-lib/hubdb.js [hunk 2]
```diff
@@ -143,6 +147,14 @@ function convertToJSON(table, rows) {
 async function downloadHubDbTable(portalId, tableId, dest) {
   const table = await fetchTable(portalId, tableId);
 
+  if (dest && fs.pathExistsSync(dest)) {
+    validateJsonFile(dest);
+  } else if (dest) {
+    validateJsonPath(dest);
+  } else {
+    dest = table.name;
```
[the remark this answers is not in the document]
Comment (anthmatic) [reply packages/cms-lib/hubdb.js]: Good call

File: packages/cms-lib/hubdb.js [hunk 3]
```diff
@@ -143,6 +147,14 @@ function convertToJSON(table, rows) {
 async function downloadHubDbTable(portalId, tableId, dest) {
   const table = await fetchTable(portalId, tableId);
 
+  dest = path.resolve(dest || `${table.name}.hubdb.json`);
```
Comment (gcorne) [inline packages/cms-lib/hubdb.js:150]: Where is `getCwd()` called to resolve the fallback relative to `getCwd()`?

Comment (anthmatic) [reply packages/cms-lib/hubdb.js]: Ah, thanks. I thought that `path.resolve()` was enough but I see that `getCwd()` takes care of getting the correct cwd now.
